# create file on all inventory
#   ansible-playbook -vv -i inventory playbooks/lynda/ansibleEssential/2-1-tasks.yaml -e file_state=touch
# delete file on all inventory
#   ansible-playbook -vv -i inventory playbooks/lynda/ansibleEssential/2-1-tasks.yaml -e file_state=absent
---
- hosts: all
  tasks:
  - name: create a file on a remote machine
    file:
      dest: /tmp/file
      state: '{{file_state}}'
- hosts: web
  tasks:
  - name: create file on web machines
    file:
      dest: /tmp/web-file
      state: '{{file_state}}'
- hosts: all:!db
  tasks:
  - name: create file on web machines
    file:
      dest: /tmp/web-not-db-file
      state: '{{file_state}}'
- hosts: all:&backup:!web
  tasks:
  - name: create file on web machines
    file:
      dest: /tmp/backup-file
      state: '{{file_state}}'