# start from specific task
#   ansible-playbook -i inventory 2-4-tasks.yaml -e file_state=touch --start-at-task='the second task'
---
- hosts: all
  tasks:
    - name: the first task
      file:
        dest: /tmp/first-task
        state: '{{file_state}}'
    - name: the second task
      file:
        dest: /tmp/second-task
        state: '{{file_state}}'
    - name: the last task
      file:
        dest: /tmp/last-task
        state: '{{file_state}}'