AWSTemplateFormatVersion: 2010-09-09
Description: >
  Creates a S3 bucket backed by lifecycle rules.
  Deploys bucket in region where the template is uploaded.
Parameters:
  BucketName:
    Type: String
    Default: very-unique-and-differnt-bucket-name-for-lifecyclerule-testing
  LifecycleConfigTransitionDaysStandardIA:
    Type: Number
    Default: 30
  LifecycleConfigTransitionDaysGlacier:
    Type: Number
    Default: 90
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: BucketName
      Tags:
      - Key: Name
        Value: TestBucket
      LifecycleConfiguration:
        Rules:
          - Id: StandardIARule
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays:
                  Ref: LifecycleConfigTransitionDaysStandardIA
          - Id: GlacierRule
            Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays:
                  Ref: LifecycleConfigTransitionDaysGlacier