---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spike-golang
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: k8s.localhost
    http:
      paths:
      - backend:
          serviceName: spike-golang
          servicePort: 8080
        path: /spike-golang
---
apiVersion: v1
kind: Service
metadata:
  name: spike-golang
spec:
  selector:
    app: spike-golang
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spike-golang
  labels:
    app: spike-golang
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spike-golang
  template:
    metadata:
      labels:
        app: spike-golang
    spec:
      containers:
        - name: spike-golang
          image: nbuhay/spike-golang:latest
          ports:
            - containerPort: 8080