AWSTemplateFormatVersion: 2010-09-09
Description: >
  Creates a generic S3 bucket for putObject.js.
  Deploys bucket in region where the template is uploaded.
Parameters:
  BucketName:
    Type: String
    Default: nodejs-aws-sdk-object-upload
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: BucketName