AWSTemplateFormatVersion: 2010-09-09
Description: "Generic VPC creation with public and private subnets."
Parameters:
  VPCCIDR:
    Type: String
    Default: 10.0.0.0/16
  PrivSub1CIDR:
    Type: String
    Default: 10.0.0.0/24
  PubSub1CIDR:
    Type: String
    Default: 10.0.1.0/24
  PrivSub2CIDR:
    Type: String
    Default: 10.0.2.0/24
  PubSub2CIDR:
    Type: String
    Default: 10.0.3.0/24
  PrivSub3CIDR:
    Type: String
    Default: 10.0.4.0/24
  PubSub3CIDR:
    Type: String
    Default: 10.0.5.0/24
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
  PrivSub1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      MapPublicIpOnLaunch: false
      CidrBlock:
        Ref: PrivSub1CIDR
  PubSub1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      MapPublicIpOnLaunch: true
      CidrBlock:
        Ref: PubSub1CIDR
  PrivSub2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      MapPublicIpOnLaunch: false
      CidrBlock:
        Ref: PrivSub2CIDR
  PubSub2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      MapPublicIpOnLaunch: true
      CidrBlock:
        Ref: PubSub2CIDR
  PrivSub3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone: !Select
        - 2
        - Fn::GetAZs: !Ref AWS::Region
      MapPublicIpOnLaunch: false
      CidrBlock:
        Ref: PrivSub3CIDR
  PubSub3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone: !Select
        - 2
        - Fn::GetAZs: !Ref AWS::Region
      MapPublicIpOnLaunch: true
      CidrBlock:
        Ref: PubSub3CIDR
Outputs:
  VPCID:
    Description: "ID of VPC created by this template."
    Value:
      Ref: VPC
    Export:
      Name: VPCID
  PrivSub1ID:
    Description: "ID of private subnet 1 residing in this template's VPC."
    Value:
      Ref: PrivSub1
    Export:
      Name: PrivSub1ID
  PubSub1ID:
    Description: "ID of public subnet 1 residing in this template's VPC."
    Value:
      Ref: PubSub1
    Export:
      Name: PubSub1ID
  PrivSub2ID:
    Description: "ID of private subnet 2 residing in this template's VPC."
    Value:
      Ref: PrivSub2
    Export:
      Name: PrivSub2ID
  PubSub2ID:
    Description: "ID of public subnet 2 residing in this template's VPC."
    Value:
      Ref: PubSub2
    Export:
      Name: PubSub2ID
  PrivSub3ID:
    Description: "ID of private subnet 3 residing in this template's VPC."
    Value:
      Ref: PrivSub3
    Export:
      Name: PrivSub3ID
  PubSub3ID:
    Description: "ID of public subnet 3 residing in this template's VPC."
    Value:
      Ref: PubSub3
    Export:
      Name: PubSub3ID