AWSTemplateFormatVersion: 2010-09-09
Description: "Generic VPC creation with public and private subnets."
Parameters:
  VPCCIDR:
    Type: String
    Default: 10.0.0.0/16
  PrivateSubnet1CIDR:
    Type: String
    Default: 10.0.0.0/24
  PublicSubnet1CIDR:
    Type: String
    Default: 10.0.1.0/24
  PrivateSubnet2CIDR:
    Type: String
    Default: 10.0.2.0/24
  PublicSubnet2CIDR:
    Type: String
    Default: 10.0.3.0/24
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      MapPublicIpOnLaunch: false
      CidrBlock:
        Ref: PrivateSubnet1CIDR
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      MapPublicIpOnLaunch: true
      CidrBlock:
        Ref: PublicSubnet1CIDR
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      MapPublicIpOnLaunch: false
      CidrBlock:
        Ref: PrivateSubnet2CIDR
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      MapPublicIpOnLaunch: true
      CidrBlock:
        Ref: PublicSubnet2CIDR
Outputs:
  VPCID:
    Description: "ID of VPC created by this template."
    Value:
      Ref: VPC
    Export:
      Name: VPCID
  PrivateSubnet1ID:
    Description: "ID of private subnet 1 residing in this template's VPC."
    Value:
      Ref: PrivateSubnet1
    Export:
      Name: PrivateSubnet1ID
  PublicSubnet1ID:
    Description: "ID of public subnet 1 residing in this template's VPC."
    Value:
      Ref: PublicSubnet1
    Export:
      Name: PublicSubnet1ID
  PrivateSubnet2ID:
    Description: "ID of private subnet 2 residing in this template's VPC."
    Value:
      Ref: PrivateSubnet2
    Export:
      Name: PrivateSubnet2ID
  PublicSubnet2ID:
    Description: "ID of public subnet 2 residing in this template's VPC."
    Value:
      Ref: PublicSubnet2
    Export:
      Name: PublicSubnet2ID