---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkinsci-blueocean
          image: jenkinsci/blueocean:latest
          ports:
            - containerPort: 8080
            - containerPort: 50000
          securityContext:
            runAsUser: 0 # permissions for docker.sock
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      # enable docker using the K8s node's docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket