---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkinsci-blueocean
          image: jenkinsci/blueocean:latest
          ports:
            - containerPort: 8080
            - containerPort: 50000